---
title: "Assignment"
description: |
  This post is built for Assignment of ISSS608 Visual Analytics and Application.
author:
  - name: LI Yuhong
date: 07-05-2021
output:
  distill::distill_article:
    self_contained: false
    toc: true
    toc_depth: 2
    number_sections: true
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# 1. Overview
## 1.1 Background
In the roughly twenty years that Tethys-based GAStech has been operating a natural gas production site in the island country of Kronos, it has produced remarkable profits and developed strong relationships with the government of Kronos. However, GAStech has not been as successful in demonstrating environmental stewardship.

In January, 2014, the leaders of GAStech are celebrating their new-found fortune as a result of the initial public offering of their very successful company. In the midst of this celebration, several employees of GAStech go missing. An organization known as the Protectors of Kronos (POK) is suspected in the disappearance, but things may not be what they seem.

## 1.2 Objective
The data used in this research is the movement and tracking data of employees. GAStech provides many of their employees with company cars for their personal and professional use, but unbeknownst to the employees, the cars are equipped with GPS tracking devices.

Based on the given tracking data for the two weeks leading up to the disappearance, as well as credit card transactions and loyalty card usage data, we will identify anomalies and suspicious behaviors of employees and then identify the owners of each credit and loyalty card.

# 2. Literature Review


# 3. Data Preparation
# 4. Data Visualisation and Analysis
# 5. Conclusion


